version: "3.7"
services:
  url_shortener:
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_DATABASE: 'url_shortener'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
        - "3307:3306"
